version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: question_bank_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-questionuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword123}
      POSTGRES_DB: ${POSTGRES_DB:-question_bank}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pdf_question_extractor/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-questionuser}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - question_network

  app:
    build:
      context: ./pdf_question_extractor
      dockerfile: Dockerfile
    container_name: question_extractor_app
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-questionuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-securepassword123}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-question_bank}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./pdf_question_extractor:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - question_network

volumes:
  postgres_data:

networks:
  question_network:
    driver: bridge